services:

  web:
    image: nginx:1.27.4
    container_name: ${CONTAINER_PREFIX}-web
    volumes:
      - './src:/var/www'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - net
    ports:
      - '${NGINX_PORT:-80}:80'
    restart: unless-stopped
    depends_on:
      - app

  app:
    build:
      args:
        - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST:-host.docker.internal}
        - XDEBUG_IDE_KEY=${XDEBUG_IDE_KEY:-PHPSTORM}
      context: docker/php
    container_name: ${CONTAINER_PREFIX}-app
    volumes:
      - './src:/var/www'
    networks:
      - net
    ports:
      - '${FPM_PORT:-9000}:9000'
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.4
    container_name: ${CONTAINER_PREFIX}-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - net
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: unless-stopped

  redis:
    image: redis:7.4.2
    container_name: ${CONTAINER_PREFIX}-redis
    networks:
      - net
    ports:
      - '${REDIS_PORT:-6379}:6379'
    restart: unless-stopped

networks:
  net:
    name: ${CONTAINER_PREFIX}-network
    driver: bridge